language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
before_install:
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in secring.gpg.enc -out local.secring.gpg -d
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in pubring.gpg.enc -out local.pubring.gpg -d
env:
  global:
    secure: ISd+aSt8+5J/cCT+eKYErWrjOXxIE6Fd4vGbW5GL+yGQEESC7Ai4HUmnussIJf3Si+IWFsHjBg+NjZ2BYncpMIkSVxKXP2oSYPNxyfp/nEnX94wGk4RZhc03K9z3UDXJ6b/uyGTzi6yZIdwy9xPBifq5KpejHeOz3HxBtYiCNYRxfhPbxEhJgaRvWCl/FSMF8wGq4USXFPEM6R/d8Vn9/EzmzwXcB2BgWOZD7PiHUVyF4T4d+o0dyFCiqPv7rn0rVA6NUyPGL2860nNKlWO5OcW3tFqv86Y+qF5dEZQWwi9EsU0oAQNkeFJ/nyUrftqcit6gx7lpOgexpF2J40a+QUoGB+rTWpWU3h0TjaJTGPcwVXizj3YOELq/THVPhpdU/FgsCU9FkoDqJGPCg+D0DQv2USjL8+T4E27bkdl2BsYYLFGczUvn/RPci2js5Uc9cKOG5ChRiPcQSNWGTqZ9ABTD8o3t166NysFVGBgHVN26epYGN7NJMmqkpJorEVhOR7suvNLZW3dqDs4of4HWVYL3I5OYx8ScKnBAFnFif3W+N2M8WFNFEjYG9z1tfT9jagvcRttnWxGV1Dq0Zakria/r9UAxKTq5ZXTbEINpqkAaSDaGy4A/GcwaIJSxmyNDE9CYxNLeHi+E26hE6iZNBqw9c0o0FHjXhSJBkSnQ1Dk=
